require 'rubygems' unless defined? Gem # rubygems is only needed in 1.8

require 'yaml'
require 'plist'

config_file = 'config.yml'
Rake::TaskManager.record_task_metadata = true

desc 'something for you
yeah baby this description is for you baby'
task :something do |task|
  File.open('log.txt', 'w') { |file| file.write('your text') }
  puts 'done with something'
end

desc 'another thing
but quite large actually'
task :another_thing do |task|
  File.open('another.txt', 'w') { |file| file.write('your text') }
  puts 'done with another thing'
end

if $0 == __FILE__
  Rake.application['populate'].invoke() #all tasks
end