require 'rubygems' unless defined? Gem # rubygems is only needed in 1.8

require 'yaml'
require 'plist'

Rake::TaskManager.record_task_metadata = true

desc 'something for you
yeah baby this description is for you baby'
task :something do |task|
  puts 'done with something'
end

desc 'another thing
but quite large actually'
task :another_thing do |task|
  puts 'done with another thing'
end